In [15]:
# create a single list from list of lists
l = [[1, 2, 3], [4, 5, 6], [7], [8, 9]]

In [3]:
flat_list = [item for sublist in l for item in sublist]
print (flat_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
flatten = lambda l: [item for sublist in l for item in sublist]

In [29]:
L = [[[1, 2, 3], [4, 5]], 6]
def flatten(l):
    for el in l:
        if isinstance(el, collections.Iterable) and not isinstance(el, (str, bytes)):
            yield from flatten(el)
        else:
            yield el

s1 = flatten(L)

In [14]:
#sort the value of dist 
import operator
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x = sorted(x.items(), key=operator.itemgetter(1))
print (sorted_x)
#sort the key of dist
sort_x1 = sorted(x.items(), key=operator.itemgetter(0))
print(sort_x1)

[(0, 0), (2, 1), (1, 2), (4, 3), (3, 4)]
[(0, 0), (1, 2), (2, 1), (3, 4), (4, 3)]


In [21]:
a = [1,2,1,1,3,2]
s = (1 if x ==1 else 2 if x == 2 else 3 for x in a)
print (s)
print ([*{x for x in a}]) # remove the duplicates and sorting it
print (sum([*{x for x in a}])) # removing the duplicates and sorting & sum the list values
print (*(map(lambda x: x+1, a))) # adding values to lists elemments


<generator object <genexpr> at 0x7fdb5c932620>
[1, 2, 3]
6
2 3 2 2 4 3


In [35]:
t = [1, 2, 3, 1, 2, 5, 6, 7, 8]
s = [1, 2, 3,1,2,1,1,1,1,]
print (sorted(list(set(t) - set(s)))) # sorting the lists and remove the common values 

from collections import OrderedDict
print(list(OrderedDict.fromkeys(t))) # sorting the list values
list1 = list(zip(t, s))
print (list1) # convert two lists into list of tuples
print(dict(zip(t, s))) # convert two lists into dictionary 
numbers = range (1,50)
numbers = [n for n in numbers if n >= 20]
print (numbers)
for i, n in enumerate(numbers):
    if n < 20 :
        print ("do something") 
        numbers[i] = None
numbers1 = [n for n in numbers if n is not None]
print (numbers1)
#d = {key: value for (key, value) in iteritems()}

[5, 6, 7, 8]
[1, 2, 3, 5, 6, 7, 8]
[(1, 1), (2, 2), (3, 3), (1, 1), (2, 2), (5, 1), (6, 1), (7, 1), (8, 1)]
{1: 1, 2: 2, 3: 3, 5: 1, 6: 1, 7: 1, 8: 1}
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [38]:
import itertools
print(list(itertools.combinations('a', 10)))

[]


list_of_five = range(0,5)   
swap_list_list = [[]]

for swap in list_of_five:

    temp_lists = []

    for list_stub in swap_list_list:

        this_list = copy.copy(list_stub)

        this_list.append(swap)

        temp_lists.append(this_list)

	temp_lists.append(list_stub)

    swap_list_list = temp_lists

print swap_list_list

In [42]:
import copy
list_of_five = range(0,5)   
swap_list_list = [[]]

for swap in list_of_five:

    temp_lists = []

    for list_stub in swap_list_list:

        this_list = copy.copy(list_stub)

        this_list.append(swap)

        temp_lists.append(this_list)

    temp_lists.append(list_stub)

    swap_list_list = temp_lists

print (swap_list_list)

[[0, 1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4], [3, 4], [4], []]


In [16]:
list11 = [1, 2, 3,1,2,1,1,1,1,2]
st = 'reddi bhaskara reddy'
st1 = st.split(' ')
print (st1)
indices = [i for i, x in enumerate(list11) if x == 1]
indices1 = [i for i, x in enumerate(st) if x == 'd']
print (indices) # finding the all occurances (index) of the value
print (indices1) # finding the all occurances (index) of the char

['reddi', 'bhaskara', 'reddy']
[0, 3, 5, 6, 7, 8]
[2, 3, 17, 18]


In [14]:
# list modifications while doing the iterations 
mylist = [1,2,3,1,2,3,1,2,3,2,1,1]
d =0
a = []
for i in mylist[::3]:   #skiping every first two elements 
    d += i    #sum of the every 
    a.append(i) # appending 
print (d)
print (a)
    

5
[1, 1, 1, 2]


In [18]:
#You could do it using np.sort to find the 10th largest value, and then use np.where to flag the array.
import numpy as np
#a = np.random.rand(30)
a = list(range(30))
a_10 = np.sort(a)[-10]
a_new = np.where(a >= a_10, 1, 0)

print(a) # Print the original
print(a_10)
print(a_new) # Print the boolean array
#EDIT: A single-line, in-place operation is thus

a = np.where(a >= np.sort(a)[-10], 1, 0)

#EDIT2: The answer can be extended to 2D. I made a 6x6 matrix, where I flag per row the 3 largest values with a 1.

# 2D example, save top3 per 
a = np.random.rand(6, 6)

a_3 = np.sort(a, axis=1)[:,-3]
a_new = np.where(a >= a_3[:,None], 1, 0)

print(a)
print(a_new)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
20
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[[0.78873309 0.14183463 0.28484904 0.8554438  0.27621882 0.88471557]
 [0.90409686 0.97882739 0.7366934  0.85350962 0.36512521 0.53600612]
 [0.24667439 0.35486899 0.24062325 0.96494182 0.0836016  0.73006679]
 [0.43045527 0.57610912 0.378232   0.25012087 0.33762047 0.39123115]
 [0.39270119 0.79255867 0.90376533 0.94838568 0.11180983 0.33645894]
 [0.76610786 0.460743   0.47917075 0.95700756 0.90472827 0.53155657]]
[[1 0 0 1 0 1]
 [1 1 0 1 0 0]
 [0 1 0 1 0 1]
 [1 1 0 0 0 1]
 [0 1 1 1 0 0]
 [1 0 0 1 1 0]]


In [7]:
#Pairwise separate the list
from itertools import *

def pairwise(iterable):
    a = iter(iterable)
    return zip(a, a)

for x, y in pairwise([1,2,1,2,1,2,1,2]):
    print ("%d + %d = %d" % (x, y, x + y))

1 + 2 = 3
1 + 2 = 3
1 + 2 = 3
1 + 2 = 3


In [43]:
data = [[1,2,3], [1,1,6], [7,8,9]]
sorted_by_second = sorted(data, key=lambda tup: tup[2]) #sorting based on the list based on the index
print (sorted_by_second)
sort_x1 = sorted(data, key=operator.itemgetter(1)) #sorting based on the list based on the index
print(sort_x1)

[[1, 2, 3], [1, 1, 6], [7, 8, 9]]
[[1, 1, 6], [1, 2, 3], [7, 8, 9]]


In [17]:
import operator
data1 = ((1,2,3), (4,1,6), (7,8,1))
#sorted_by_second = sorted(data, key=lambda lst: lst(1))
sort_x4 = sorted(data1, key=operator.itemgetter(2)) #sorting the tuples based on the index
print(tuple(sort_x4))#displaying the which type want if tuple or list
sort_x5 = sorted(data1, key=operator.itemgetter(2))
print(list(sort_x5))

((7, 8, 1), (1, 2, 3), (4, 1, 6))
[(7, 8, 1), (1, 2, 3), (4, 1, 6)]


In [1]:
T1 = (('13', '17', '18', '21', '32'),
      ('07', '11', '13', '14', '28'),
      ('01', '05', '06', '08', '15', '16'))
T2 = [list(map(int, x)) for x in T1]
print (T2) # convert the string of tuples to list of integers 

[[13, 17, 18, 21, 32], [7, 11, 13, 14, 28], [1, 5, 6, 8, 15, 16]]


In [10]:
c1 = [1, 6, 7, 10, 13, 28, 32, 41, 58, 63]
c2 = [[13, 17, 18, 21, 32], [7, 11, 13, 14, 28], [1, 5, 6, 8, 15, 16]]

c3 = [list(filter(lambda x: x in c1, sublist)) for sublist in c2]
#c3 = [list(filter(lambda x: x in c1, sublist)) for sublist in c2]
print (c3) #intersection of two lists

[[13, 32], [7, 13, 28], [1, 6]]


In [11]:
print (c3)

[[13, 32], [7, 13, 28], [1, 6]]


In [19]:
x = [1,2,3,2,2,2,3,4]
print(list(filter(lambda a: a != 2, x))) #remove the first occurrence of value in a list and all those elements

[1, 3, 3, 4]


In [21]:
a = [1,1,2,1,2,2,1,2,3,3,4,5,5,3,2,3,4,5]
from itertools import groupby
b = sorted(a, key = lambda x: x)
d = [len(list(grp)) for k, grp in groupby(b)]
print (d)
c = [len(list(grp)) for k, grp in groupby(sorted(a, key = lambda x: x))]#sorting the list and find the number of occurnece
print(c)



[4, 5, 4, 2, 3]
[4, 5, 4, 2, 3]


In [20]:
Y = [ 0,   1,   1,    0,   1,   2,   2,   0,   1]
k = sorted(Y, key = lambda x: x)
print (k) # Sorting the list of items

[0, 0, 0, 1, 1, 1, 1, 2, 2]


In [16]:
a = [1,1,2,1,2,2,1,2,3,3,4,5,5,3,2,3,4,5]
i = list(iter(a))
print (i,'\n', a)
rr = dict(zip(i,i))
print(rr)


[1, 1, 2, 1, 2, 2, 1, 2, 3, 3, 4, 5, 5, 3, 2, 3, 4, 5] 
 [1, 1, 2, 1, 2, 2, 1, 2, 3, 3, 4, 5, 5, 3, 2, 3, 4, 5]
{1: 1, 2: 2, 3: 3, 4: 4, 5: 5}


In [21]:
a = [1,2,3,2,1,5,6,5,5,5]

import collections
print ([item for item, count in collections.Counter(a).items() if count >= 1]) #display unique elements

seen = set()
uniq = []
for x in a:
    if x not in seen:
        uniq.append(x)
        seen.add(x)
print(uniq)
print(seen)


[1, 2, 3, 5, 6]
[1, 2, 3, 5, 6]
{1, 2, 3, 5, 6}


In [17]:
a = [66.25, 333, 334, 1, 1234.5]
b = sorted(a, reverse=True)
print (b)
c = reversed(a)
print(list(c))

[1234.5, 334, 333, 66.25, 1]
[1234.5, 1, 334, 333, 66.25]


In [18]:
l = [[1,2,3],[4,5,6],[7,8,9]] #Transpose list of lists
z = list(map(list, zip(*l)))
print(z)

[[1, 4, 7], [2, 5, 8], [3, 6, 9]]


In [22]:
 a = [[1,2,3],[4,5,6],[7,8,9,10]] #All combinations of a list of lists
import itertools
z = list(itertools.product(*a))
print (z)

[(1, 4, 7), (1, 4, 8), (1, 4, 9), (1, 4, 10), (1, 5, 7), (1, 5, 8), (1, 5, 9), (1, 5, 10), (1, 6, 7), (1, 6, 8), (1, 6, 9), (1, 6, 10), (2, 4, 7), (2, 4, 8), (2, 4, 9), (2, 4, 10), (2, 5, 7), (2, 5, 8), (2, 5, 9), (2, 5, 10), (2, 6, 7), (2, 6, 8), (2, 6, 9), (2, 6, 10), (3, 4, 7), (3, 4, 8), (3, 4, 9), (3, 4, 10), (3, 5, 7), (3, 5, 8), (3, 5, 9), (3, 5, 10), (3, 6, 7), (3, 6, 8), (3, 6, 9), (3, 6, 10)]


In [33]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[0,4,1]])
np.sort(a.view('i8,i8,i8'), order=['f0'], axis=0).view(np.int)

array([[0, 4, 1],
       [1, 2, 3],
       [4, 5, 6]])

In [41]:
import functools
l = [15, 18, 2, 36, 12, 78, 5, 6, 9]
print (functools.reduce(lambda x, y: x + y, l) / len(l)) #avg of list

20.11111111111111


In [17]:
a = [1,2,3,2,1,5,6,5,5,5]
l = list(sorted(a, key=lambda x:x))
print (l)

import operator

la = [1,2,3,2,1,5,6,5,5,5]
la1 = [all(la[i] <= la[i+1] for i in range(len(la)-1))]
print (la1)

[1, 1, 2, 2, 3, 5, 5, 5, 5, 6]
[False]


In [15]:
import pandas as pd
df = pd.DataFrame( {'a':['A','A','B','B','B','C', 'C'], 'b':[1,2,5,5,4,6,4], 'c':[1,2,3,1,2,3,1]})
df.groupby('a')['c'].apply(list)

a
A       [1, 2]
B    [3, 1, 2]
C       [3, 1]
Name: c, dtype: object

In [16]:
l = [{'a': 123, 'b': 1234}, {'a': 3222, 'b': 1234}, {'a': 123, 'b': 1234}]
[dict(t) for t in set([tuple(d.items()) for d in l])] #remove the duplicate in the dicts of list

[{'a': 3222, 'b': 1234}, {'a': 123, 'b': 1234}]

In [16]:
l = ['Name1', '7.3', '6.9', '6.6\n', '6.6', '6.1', '6.4', '7.3\n']
l = map(lambda s: s.strip(), l)
print (list(l)) #If you want to remove \n from all the elements

['Name1', '7.3', '6.9', '6.6', '6.6', '6.1', '6.4', '7.3']
