In [15]:
# create a single list from list of lists
l = [[1, 2, 3], [4, 5, 6], [7], [8, 9]]

In [3]:
flat_list = [item for sublist in l for item in sublist]
print (flat_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [7]:
flatten = lambda l: [item for sublist in l for item in sublist]

In [29]:
L = [[[1, 2, 3], [4, 5]], 6]
def flatten(l):
    for el in l:
        if isinstance(el, collections.Iterable) and not isinstance(el, (str, bytes)):
            yield from flatten(el)
        else:
            yield el

s1 = flatten(L)

In [14]:
#sort the value of dist 
import operator
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x = sorted(x.items(), key=operator.itemgetter(1))
print (sorted_x)
#sort the key of dist
sort_x1 = sorted(x.items(), key=operator.itemgetter(0))
print(sort_x1)

[(0, 0), (2, 1), (1, 2), (4, 3), (3, 4)]
[(0, 0), (1, 2), (2, 1), (3, 4), (4, 3)]


In [21]:
a = [1,2,1,1,3,2]
s = (1 if x ==1 else 2 if x == 2 else 3 for x in a)
print (s)
print ([*{x for x in a}]) # remove the duplicates and sorting it
print (sum([*{x for x in a}])) # removing the duplicates and sorting & sum the list values
print (*(map(lambda x: x+1, a))) # adding values to lists elemments


<generator object <genexpr> at 0x7fdb5c932620>
[1, 2, 3]
6
2 3 2 2 4 3


In [35]:
t = [1, 2, 3, 1, 2, 5, 6, 7, 8]
s = [1, 2, 3,1,2,1,1,1,1,]
print (sorted(list(set(t) - set(s)))) # sorting the lists and remove the common values 

from collections import OrderedDict
print(list(OrderedDict.fromkeys(t))) # sorting the list values
list1 = list(zip(t, s))
print (list1) # convert two lists into list of tuples
print(dict(zip(t, s))) # convert two lists into dictionary 
numbers = range (1,50)
numbers = [n for n in numbers if n >= 20]
print (numbers)
for i, n in enumerate(numbers):
    if n < 20 :
        print ("do something") 
        numbers[i] = None
numbers1 = [n for n in numbers if n is not None]
print (numbers1)
#d = {key: value for (key, value) in iteritems()}

[5, 6, 7, 8]
[1, 2, 3, 5, 6, 7, 8]
[(1, 1), (2, 2), (3, 3), (1, 1), (2, 2), (5, 1), (6, 1), (7, 1), (8, 1)]
{1: 1, 2: 2, 3: 3, 5: 1, 6: 1, 7: 1, 8: 1}
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
[20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [38]:
import itertools
print(list(itertools.combinations('a', 10)))

[]


list_of_five = range(0,5)   
swap_list_list = [[]]

for swap in list_of_five:

    temp_lists = []

    for list_stub in swap_list_list:

        this_list = copy.copy(list_stub)

        this_list.append(swap)

        temp_lists.append(this_list)

	temp_lists.append(list_stub)

    swap_list_list = temp_lists

print swap_list_list

In [42]:
import copy
list_of_five = range(0,5)   
swap_list_list = [[]]

for swap in list_of_five:

    temp_lists = []

    for list_stub in swap_list_list:

        this_list = copy.copy(list_stub)

        this_list.append(swap)

        temp_lists.append(this_list)

    temp_lists.append(list_stub)

    swap_list_list = temp_lists

print (swap_list_list)

[[0, 1, 2, 3, 4], [1, 2, 3, 4], [2, 3, 4], [3, 4], [4], []]


In [16]:
list11 = [1, 2, 3,1,2,1,1,1,1,2]
st = 'reddi bhaskara reddy'
st1 = st.split(' ')
print (st1)
indices = [i for i, x in enumerate(list11) if x == 1]
indices1 = [i for i, x in enumerate(st) if x == 'd']
print (indices) # finding the all occurances (index) of the value
print (indices1) # finding the all occurances (index) of the char

['reddi', 'bhaskara', 'reddy']
[0, 3, 5, 6, 7, 8]
[2, 3, 17, 18]


In [14]:
# list modifications while doing the iterations 
mylist = [1,2,3,1,2,3,1,2,3,2,1,1]
d =0
a = []
for i in mylist[::3]:   #skiping every first two elements 
    d += i    #sum of the every 
    a.append(i) # appending 
print (d)
print (a)
    

5
[1, 1, 1, 2]


In [18]:
#You could do it using np.sort to find the 10th largest value, and then use np.where to flag the array.
import numpy as np
#a = np.random.rand(30)
a = list(range(30))
a_10 = np.sort(a)[-10]
a_new = np.where(a >= a_10, 1, 0)

print(a) # Print the original
print(a_10)
print(a_new) # Print the boolean array
#EDIT: A single-line, in-place operation is thus

a = np.where(a >= np.sort(a)[-10], 1, 0)

#EDIT2: The answer can be extended to 2D. I made a 6x6 matrix, where I flag per row the 3 largest values with a 1.

# 2D example, save top3 per 
a = np.random.rand(6, 6)

a_3 = np.sort(a, axis=1)[:,-3]
a_new = np.where(a >= a_3[:,None], 1, 0)

print(a)
print(a_new)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
20
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
[[0.78873309 0.14183463 0.28484904 0.8554438  0.27621882 0.88471557]
 [0.90409686 0.97882739 0.7366934  0.85350962 0.36512521 0.53600612]
 [0.24667439 0.35486899 0.24062325 0.96494182 0.0836016  0.73006679]
 [0.43045527 0.57610912 0.378232   0.25012087 0.33762047 0.39123115]
 [0.39270119 0.79255867 0.90376533 0.94838568 0.11180983 0.33645894]
 [0.76610786 0.460743   0.47917075 0.95700756 0.90472827 0.53155657]]
[[1 0 0 1 0 1]
 [1 1 0 1 0 0]
 [0 1 0 1 0 1]
 [1 1 0 0 0 1]
 [0 1 1 1 0 0]
 [1 0 0 1 1 0]]


In [26]:
#Pairwise separate the list
from itertools import *

def pairwise(iterable):
    a = iter(iterable)
    return zip(a, a)

for x, y in pairwise([1,2,1,2,1,2,1,2]):
    print ("%d + %d = %d" % (x, y, x + y))

1 + 2 = 3
1 + 2 = 3
1 + 2 = 3
1 + 2 = 3


In [43]:
data = [[1,2,3], [1,1,6], [7,8,9]]
sorted_by_second = sorted(data, key=lambda tup: tup[2]) #sorting based on the list based on the index
print (sorted_by_second)
sort_x1 = sorted(data, key=operator.itemgetter(1)) #sorting based on the list based on the index
print(sort_x1)

[[1, 2, 3], [1, 1, 6], [7, 8, 9]]
[[1, 1, 6], [1, 2, 3], [7, 8, 9]]


In [46]:
import operator
data1 = ((1,2,3), (4,1,6), (7,8,1))
#sorted_by_second = sorted(data, key=lambda lst: lst(1))
sort_x4 = sorted(data1, key=operator.itemgetter(2)) #sorting the tuples based on the index
print(tuple(sort_x4)) #displaying the which type want if tuple or list

((7, 8, 1), (1, 2, 3), (4, 1, 6))
